{
 "title": "dashboard final",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Chosen_visualization",
    "query": "all_data,noise_level,temperature,humidity,uv_level,luminosity,carbon_monoxide_level,polution_particles_ppm"
   },
   { "name": "display", "query": "marker,heatmap" },
   {
    "name": "Day",
    "query": "SELECT DISTINCT\n  FORMAT('%s-%s-%s', \n    extract(YEAR from \"timestamp\") ,\n    extract(MONTH from \"timestamp\"),\n    extract(DAY from \"timestamp\")) AS formatted_date\nFROM dev.data_points"
   },
   {
    "name": "trip_id",
    "query": "SELECT DISTINCT trip_id\nFROM dev.data_points\nWHERE DATE(\"timestamp\") IN (${Day})\n"
   },
   { "name": "min_noise_level", "query": "0" },
   { "name": "max_noise_level", "query": "500" },
   { "name": "min_pretended_temperature", "query": "10" },
   { "name": "max_pretended_temperature", "query": "35" },
   { "name": "min_humidity", "query": "0" },
   { "name": "max_humidity", "query": "100" },
   { "name": "min_uv_level", "query": "0" },
   { "name": "max_uv_level", "query": "20" },
   { "name": "min_luminosity", "query": "0" },
   { "name": "max_luminosity", "query": "3000" },
   { "name": "min_carbon_monoxide_level", "query": "0" },
   { "name": "max_carbon_monoxide_level", "query": "10" },
   { "name": "min_polution_particles_pmm", "query": "0" },
   { "name": "max_polution_particles_pmm", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Map Visualization",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\" ,\r\n  latitude,\r\n  longitude,\r\n  speed ,\r\n  course,\r\n  altitute ,\r\n  satellites_in_use,\r\n  fix_type,\r\n  hdop,\r\n  vdop,\r\n  pdop,\r\n  id,\r\n  trip_id,\r\n  noise_level ,\r\n  temperature ,\r\n  humidity ,\r\n  uv_level,\r\n  luminosity ,\r\n  carbon_monoxide_level ,\r\n  polution_particles_ppm \r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'all_data')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  noise_level \r\n  \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'noise_level') \r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n   "
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  temperature \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'temperature')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  humidity \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'humidity')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  uv_level\r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'uv_level')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  luminosity \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'luminosity')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  carbon_monoxide_level \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'carbon_monoxide_level')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  polution_particles_ppm \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'polution_particles_ppm')\r\n   AND('$display'='marker')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\" ,\r\n  latitude,\r\n  longitude,\r\n  speed ,\r\n  course,\r\n  altitute,\r\n  satellites_in_use,\r\n  fix_type,\r\n  hdop,\r\n  vdop,\r\n  pdop,\r\n  id,\r\n  trip_id,\r\n  noise_level ,\r\n  temperature ,\r\n  humidity ,\r\n  uv_level,\r\n  luminosity ,\r\n  carbon_monoxide_level ,\r\n  polution_particles_ppm \r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'all_data')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  noise_level \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'noise_level') \r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  temperature \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'temperature')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  humidity \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'humidity')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  uv_level\r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'uv_level')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  luminosity \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'luminosity')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})\r\n"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  carbon_monoxide_level \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'carbon_monoxide_level')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})"
    },
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  \"timestamp\",\r\n  latitude,\r\n  longitude,\r\n  polution_particles_ppm \r\n\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\n   AND (noise_level > $min_noise_level AND noise_level < $max_noise_level )\r\n   AND (temperature > $min_pretended_temperature  AND temperature < $max_pretended_temperature )\r\n   AND (humidity > $min_humidity AND humidity < $max_humidity)\r\n   AND (uv_level>$min_uv_level AND uv_level< $max_uv_level )\r\n   AND (luminosity>$min_luminosity  AND luminosity<$max_luminosity)\r\n   AND (carbon_monoxide_level>=$min_carbon_monoxide_level AND carbon_monoxide_level<=$max_carbon_monoxide_level )\r\n   AND (polution_particles_ppm>=$min_polution_particles_pmm AND polution_particles_ppm<=$max_polution_particles_pmm )\r\n   AND ('$Chosen_visualization' = 'polution_particles_ppm')\r\n   AND('$display'='heatmap')\r\n   AND DATE(\"timestamp\") IN (${Day})"
    }
   ]
  },
  { "title": "Data by the selected trip_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Ciclist_velocity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(speed) as Minimum,\r\n  avg(speed) as Average,\r\n  max(speed) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "Noise_level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(noise_level) as Minimum,\r\n  avg(noise_level) as Average,\r\n  max(noise_level) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n   trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(temperature) as Minimum,\r\n  avg(temperature) as Average,\r\n  max(temperature) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(humidity) as Minimum,\r\n  avg(humidity) as Average,\r\n  max(humidity) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "uv_level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(uv_level) as Minimum,\r\n  avg(uv_level) as Average,\r\n  max(uv_level) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "luminosity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(luminosity) as Minimum,\r\n  avg(luminosity) as Average,\r\n  max(luminosity) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "carbon_monoxide_level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(luminosity) as Minimum,\r\n  avg(luminosity) as Average,\r\n  max(luminosity) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  {
   "title": "polution_particles_ppm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(polution_particles_ppm) as Minimum,\r\n  avg(polution_particles_ppm) as Average,\r\n  max(polution_particles_ppm) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  trip_id IN ($trip_id)\r\nLIMIT 2000;"
    }
   ]
  },
  { "title": "Data by the selected day", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Ciclist_velocity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  min(speed) as Minimum,\r\n  avg(speed) as Average,\r\n  max(speed) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day});"
    }
   ]
  },
  {
   "title": "Noise_level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(noise_level) as Minimum,\r\n  avg(noise_level) as Average,\r\n  max(noise_level) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day});; \r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(temperature) as Minimum,\r\n  avg(temperature) as Average,\r\n  max(temperature) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day});\r\n"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT\r\n  min(humidity) as Minimum, \r\n  avg(humidity) as Average,\r\n  max(humidity) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n    DATE(\"timestamp\") in (${Day});"
    }
   ]
  },
  {
   "title": "uv_level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(uv_level) as Minimum,\r\n  avg(uv_level) as Average,\r\n  max(uv_level) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day});"
    }
   ]
  },
  {
   "title": "luminosity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(luminosity) as Minimum,\r\n  avg(luminosity) as Average,\r\n  max(luminosity) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day});"
    }
   ]
  },
  {
   "title": "carbon_monoxide_level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Selecionando colunas específicas da tabela dev.data_points\r\nSELECT \r\n  min(luminosity) as Minimum,\r\n  avg(luminosity) as Average,\r\n  max(luminosity) as Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day});"
    }
   ]
  },
  {
   "title": "polution_particles_ppm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  MIN(polution_particles_ppm) AS Minimum,\r\n  AVG(polution_particles_ppm) AS Average,\r\n  MAX(polution_particles_ppm) AS Maximum\r\nFROM \r\n  dev.data_points \r\nWHERE \r\n  DATE(\"timestamp\") in (${Day}); "
    }
   ]
  }
 ]
}